routes/web.php
<?php

use App\Http\Controllers\LocaleController;

/*
 * Global Routes
 *
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', [LocaleController::class, 'change'])->name('locale.change');

/*
 * Frontend Routes
 */
Route::group(['as' => 'frontend.'], function () {
    includeRouteFiles(__DIR__.'/frontend/');
});

/*
 * Backend Routes
 *
 * These routes can only be accessed by users with type `admin`
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    includeRouteFiles(__DIR__.'/backend/');
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Customer extends Model
{
    use SoftDeletes;
    
    protected $fillable = [
        'nombre', 'cuit', 'telefono',
    ];

    public function addresses() 
    {
    	return $this->hasMany('App\Models\Address');
    }
    /*
    ** Accessors y Mutators
    */
    use Traits\Mutators;
}

app/Models/Remito.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Remito extends Model
{
    
    use SoftDeletes;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'remitos';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
                  'fecha_estimada',
                  'fecha_real',
                  'product_id',
                  'address_id',
                  'cantidad',
                  'precio_unitario'
              ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
               'deleted_at'
           ];
    
    /**
     * Get the product for this model.
     *
     * @return App\Models\Product
     */
    public function product()
    {
        return $this->belongsTo('App\Models\Product','product_id');
    }

    /**
     * Get the address for this model.
     *
     * @return App\Models\Address
     */
    public function address()
    {
        return $this->belongsTo('App\Models\Address','address_id');
    }

    public function getEstadoAttribute()
    {   
        return ($this->deleted_at ? 
                '<span class="badge badge-danger">Eliminado</span>' : 
                '<span class="badge badge-success">Activo</span>'
            );
    }
}

app/Http/Controllers/Frontend/User/CustomerController.php
<?php

namespace App\Http\Controllers\Frontend\User;

use App\Http\Controllers\Controller;
use App\Models\Customer;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('frontend.user.customer');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function show(Customer $customer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customer $customer)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        //
    }
}

app/Http/Livewire/Customer/Browse.php
<?php

namespace App\Http\Livewire\Customer;

use Livewire\Component;
use Livewire\WithPagination;
use App\Models\Customer;

class Browse extends Component
{

	use WithPagination;
    protected $paginationTheme = 'bootstrap';

    public $sorted_column, $sort_direction, $data_model, $show_modal;
    public $nombre, $cuit, $telefono, $keyid;

    protected $listeners = ['modalClose' => 'closemodal'];

    protected $queryString = [
        'search' => ['except' => ''],
        'page' => ['except' => 1],
    ];
    protected $rules = [
        'nombre' => 'required|string|max:120|min:4',
        'telefono' => 'nullable|string|max:25',
        'cuit' => ''
    ];
    public $search = '';

    public $filter_active = 1;
	public $filter_removed = 0;
	public $form = [];

    public function updatingSearch()
    {
        $this->resetPage();
    }

	public function default()
    {
        $this->reset(['nombre', 'cuit', 'telefono', 'keyid']);
        $this->show_modal = 0;
    	$this->form['title'] = "Nuevo Cliente";
    	$this->form['action'] = "store";
    	$this->form['view'] = "create";
    }

    public function mount()
    {
        $this->sorted_column = 'nombre';
        $this->sort_direction = ['order' => 'asc', 'dir' => 'up'];
        $this->fill(request()->only('search', 'page'));
        $this->default();
    }

    private function filtered()
    {
    	$query = Customer::with('addresses')->withCount('addresses');
    	if($this->filter_active && $this->filter_removed){
        	$query->withTrashed();
        }elseif ($this->filter_removed) {
        	$query->onlyTrashed();
        }else {
        	$this->filter_active = "1";
        }
        if($this->search) {
            $query->whereLike('nombre', $this->search);
        }
    	return $query;
    }

    public function store()
    {
        if(auth()->user()->can('customer.create')) {

            $this->rules['cuit'] = 'required|numeric|unique:customers';

            $validated_data = $this->validate();
			
            $this->data_model = new Customer($validated_data);

            $this->data_model->save();

            $this->edit($this->data_model->id);

            session()->flash('flash_success', 'Cliente agregado correctamente.');
        }else {
            session()->flash('flash_warning', 'Usted no tiene permisos para agregar.');
        }
    }

    private function setData($id)
    {
        $this->data_model = Customer::withTrashed()->find($id);
    }

    public function edit($id)
    {
        $this->setData($id);
        $this->keyid = $this->data_model->id;
        $this->nombre = $this->data_model->nombre;
        $this->cuit = $this->data_model->cuit;
        $this->telefono = $this->data_model->telefono;
        $this->form['title'] = "Editando #{$this->keyid}";
        $this->form['action'] = "update";
        $this->form['view'] = "edit";
    }

    public function openAddresses($customer)
    {
        return redirect()->to("/customers/{$customer}/addresses");
    }

    public function editing($id)
    {
        return ($id == $this->keyid);
    }

    public function update()
    {
        if(auth()->user()->can('customer.edit')) {
            $this->rules['cuit'] = 'required|numeric|unique:customers,cuit,'.$this->keyid.',id';
            $this->validate();
            $this->data_model->nombre = $this->nombre;
            $this->data_model->cuit = $this->cuit;
            $this->data_model->telefono = $this->telefono;
            $this->data_model->save();
            $this->default();
            session()->flash('flash_success', 'Cliente actualizado correctamente.');
        }else {
            session()->flash('flash_warning', 'Usted no tiene permisos para editar.');
        }
        
    }

    public function destroy($id)
    {
        if(auth()->user()->can('customer.delete')) {
            Customer::destroy($id);
            $this->default();
            session()->flash('flash_info', 'Cliente eliminado correctamente.');
        }else {
            session()->flash('flash_warning', 'Usted no tiene permisos para eliminar.');
        }
    }

    public function restore($id)
    {
        if(auth()->user()->can('customer.edit')) {
        	$this->edit($id);

            $this->data_model->restore();
            
            session()->flash('flash_success', 'Cliente restaurada correctamente.');
        }else {
            session()->flash('flash_warning', 'Usted no tiene permisos para editar.');
        }
    }

    public function sortBy($col_name)
    {    
        $directions = collect([['order' => 'asc', 'dir' => 'up'], ['order' => 'desc', 'dir' => 'down']]);

        $new_direction = $directions->where('order','!=', $this->sort_direction['order'])->first();

        $this->sort_direction['dir'] = $new_direction['dir'];
        $this->sort_direction['order'] = $new_direction['order'];

        $this->sorted_column = $col_name;
    }

    public function render()
    {
    	$space = 'livewire.customer';
    	$list_customers = $this->filtered()->orderBy($this->sorted_column, $this->sort_direction['order'])->paginate(12);
        return view("{$space}.browse", [
        	'includes' => "{$space}.includes",
        	'list_customers' => $list_customers
        ])
            ->extends('frontend.layouts.app')
            ->section('content');
    }
}

app/Http/Livewire/Includes/Message.php
<?php

namespace App\Http\Livewire\Includes;

use Livewire\Component;

class Message extends Component
{
    public function render()
    {
        return view('livewire.includes.message');
    }
}

resources/views/livewire/customer/includes/__modal.blade.php
<div x-data="{
    show: @entangle('show_modal'), 
    open() { this.show = 1 }, 
    close() { this.show = 0;   }, 
    isOpen() { return this.show === 1 }
  }" 
  x-on:open-modal.window="open()"
>
  <template x-if="isOpen()">
    <div 
      id="modalLive" 
      class="modal fade show"
      tabindex="-1" 
      role="dialog" 
      aria-labelledby="modalLiveLabel" 
      style="display: block; padding-right: 17px;background-color: #3f42448a;"      
    >    
      <div 
        class="modal-dialog modal-lg"
        style="max-width: 90%" 
        role="document"
        @click.away="close()"
        x-show="isOpen()"
      >
        <div class="modal-content">          
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLiveLabel">DOMICILIOS DE {{ $data_model->nombre }} (#{{ $data_model->id }})</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" x-on:click="close()">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">            
            @livewire('address.address-component', ['customer' => $data_model], key('addresses_'.$data_model->id))
          </div>          
        </div>
      </div>      
    </div>    
  </template>    
</div>

  

resources/views/livewire/customer/includes/filters.blade.php
<x-frontend.card>
    <x-slot name="header">
        <i class="fas fa-search"></i> Buscador
    </x-slot>

    <x-slot name="body">

        <x-forms.get class="form-inline" wire:submit.prevent="render">

            <x-input.switch name="filter_active" id="filter_active" label="Activos" wire:model="filter_active" switchclass="success" checked="checked"/>

            <x-input.switch name="filter_removed" id="filter_removed" label="Eliminados" wire:model="filter_removed" switchclass="danger"/>

        	<x-input.search name="search" id="search" placeholder="Nombre de cliente" wire:model.debounce.800ms="search"/>

        </x-forms.get>

    </x-slot>
</x-frontend.card>

resources/views/livewire/customer/includes/form.blade.php
<x-frontend.card>
    <x-slot name="header">
        <h4 class="card-title my-2"> {{ $form['title'] }} </h4>
    </x-slot>

    <x-slot name="body">

        <x-forms.post wire:submit.prevent="{{ $form['action'] }}">

            <x-input.text name="nombre" id="nombre" :label="'Nombre de cliente'" wire:model.defer="nombre" required/>

            <x-input.number name="cuit" id="cuit" :label="'Indentificador'" wire:model.defer="cuit" placeholder="DNI / CUIL / CUIT"/>

            <x-input.phone name="telefono" id="telefono" :label="'Teléfono'" wire:model.defer="telefono"/>

            <x-button.save label="Guardar"/>

	    	@if($form['view']=='edit')
	    	<button class="btn btn-outline-secondary m-2" type="button" wire:click="default">Cancelar</button>
	    	@endif
        </x-forms.post>

    </x-slot>
</x-frontend.card>

resources/views/livewire/customer/includes/list.blade.php
<div class="card mt-2">
    <div class="card-body">
        <h4 class="card-title mb-3"> Listado de Clientes </h4>
	    <div class="table-responsive">
			<table class="table w-full">
			    <thead>
			        <tr class="bg-gray-600 text-white">
			            <th class="px-4 py-2" scope="col">#</th>
			            <th class="px-4 py-2" scope="col"><x-table.sort :label="'Nombre'" :column="'nombre'" sorted="{{$sorted_column}}" direction="{{$sort_direction['dir']}}"/></th>
			            <th class="px-4 py-2" scope="col">Identificador</th>
			            <th class="px-4 py-2" scope="col">Teléfono</th>
			            <th class="px-4 py-2" scope="col">Domicilios</th>
			            <th class="px-4 py-2" scope="col">Estado</th>
			            <th class="px-4 py-2" scope="col">acciones</th>
			        </tr>
			    </thead>
			    <tbody>
			    	@foreach($list_customers as $cust)
	                <tr @if($this->editing($cust->id))class="font-weight-bold bg-light text-dark" @endif>
	                    <th scope="row">{{$cust->id}}</th>
	                    <td>{{$cust->nombre}}</td>
	                    <td>{{$cust->cuit}}</td>
	                    <td><x-utils.link target="_blank" class="btn btn-link" icon="fab fa-whatsapp" href="https://api.whatsapp.com/send?phone={{preg_replace('/(\+54 9 )?[\(\)\-\s]+/', null, $cust->telefono)}}" text="{{$cust->telefono}}"/></td>
	                    <td class="d-flex justify-content-center">
	                    @if($cust->addresses->count()>0)
	                    	<x-utils.link class="btn btn-warning" icon="fas fa-list" wire:click="openAddresses({{ $cust->id }})">
	                    		<span class="badge badge-light">{{ $cust->addresses->count() }}</span>
	                    	</x-utils.link>
	                    @else
	                    	<x-utils.link href="javascript:void(0);" class="btn btn-sm btn-primary" icon="fas fa-plus" wire:click="openAddresses({{ $cust->id }})"/>
	                    @endif
	                    </td>
	                    <td><h5>{!! $cust->estado !!}</h5></td>
	                    <td class="d-flex justify-content-center">			                    	
	                    	@if($cust->deleted_at)
	                    	<x-action.restore wire:click="restore({{ $cust->id }})"/>
	                    	@else
	                    	<x-action.edit wire:click="edit({{ $cust->id }})"/>
	                    	<x-action.delete wire:click="destroy({{ $cust->id }})"/>
	                    	@endif			                    	
	                    </td>
	                </tr>
	                @endforeach
			    </tbody>
			    <tfoot>
	            	<tr>
	            		<td colspan="8">
	            			@if(session()->get('flash_info'))
							    <x-utils.alert type="info" class="header-message">
							        {{ session()->get('flash_info') }}
							    </x-utils.alert>
							@endif
	            		</td>
	            	</tr>
	            </tfoot>
			</table>
			{{ $list_customers->links() }}
		</div>
	</div>
</div>

resources/views/livewire/customer/includes/modal.blade.php
<div 
  x-data
  id="modalLive" 
  class="modal fade show"
  tabindex="-1" 
  role="dialog" 
  aria-labelledby="modalLiveLabel" 
  style="display: block; padding-right: 17px;background-color: #3f42448a;"      
>    
  <div 
    class="modal-dialog modal-lg"
    style="max-width: 90%" 
    role="document"
    id="modalContent"
    x-on:click.away="$wire.closemodal()"
  >
    <div class="modal-content">          
      <div class="modal-header">
        <h5 class="modal-title" id="modalLiveLabel">DOMICILIOS DE {{ $data_model->nombre }} (#{{ $data_model->id }})</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" wire:click="$emitUp('modalClose')">
          <span aria-hidden="true">x</span>
        </button>
      </div>
      <div class="modal-body">            
        @livewire('address.address-component', ['customer' => $data_model], key('addresses_'.$data_model->id))
      </div>   
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" wire:click="$emitUp('modalClose')">Cerrar</button>
      </div>       
    </div>
  </div>      
</div> 